[build]
builder = "nixpacks"
buildCommand = "npm install && cd shared && npm run build && cd ../client && npm install && npm run build"

[deploy]
startCommand = "cd client && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
