[build]
builder = "nixpacks"
buildCommand = "npm install && cd shared && npm run build && cd ../server && npm install && npm run build && npx prisma generate"

[deploy]
startCommand = "cd server && npx prisma migrate deploy && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production" 