[build]
builder = "nixpacks"
buildCommand = "npm install && cd shared && npm run build && cd ../server && npm install && npm run build"

[deploy]
startCommand = "cd server && migrate:prod && npm run start"
restartPolicyType = "on_failure"
