POST http://localhost:8080/api/leads/create
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWRzN2VrbGYwMDAxcnA4NHB2dDNhbzNvIiwiZW1haWwiOiJhZGlzZW1hbW8yMTFAZGV2LmNvbSIsInBlcm1pc3Npb25zIjpbIk1BTkFHRV9PV05fTEVBRFMiLCJFRElUX1dPUktTUEFDRV9MRUFEUyIsIkRFTEVURV9XT1JLU1BBQ0VfTEVBRFMiLCJBU1NJR05fTEVBRFMiLCJNQU5BR0VfVVNFUlMiLCJNQU5BR0VfQklMTElORyJdLCJpYXQiOjE3NTQwNjI1NTYsImV4cCI6MTc1NDA2NjE1Nn0.3pasnLUcf4Y5ERLyk3kOWgNdGL1a8t-2hsZ4-nnLjEA


{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phone": "+1234567890",
  "company": "Example Inc.",
  "jobTitle": "Software Engineer",
  "industry": "Technology",
  "status": "NEW",
  "website": "https://example.com",
  "address": "123 Main St",
  "city": "Anytown",
  "state": "CA",
  "zipCode": "12345",
  "country": "USA",
  "workspaceId": "cmds7eklb0000rp84oif946tf"
}

###

POST http://localhost:8080/api/leads/create
Content-Type: application/json

{"simple":"test"}