export const industriesList = [
  "Technology",
  "Healthcare",
  "Finance",
  "Education",
  "Manufacturing",
  "Retail",
  "Real Estate",
  "Transportation",
  "Energy",
  "Media & Entertainment",
  "Food & Beverage",
  "Automotive",
  "Construction",
  "Pharmaceuticals",
  "Telecommunications",
  "Aerospace",
  "Hospitality",
  "Legal Services",
  "Consulting",
  "Non-Profit",
];
