[build]
builder = "nixpacks"
buildCommand = "npm install && cd shared && npm run build && cd ../server && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd server && npm run migrate:prod && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
