[build]
builder = "nixpacks"
buildCommand = "npm install && cd ../shared && npm run build && cd ../server && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"
