// This file is generated by the generate-enums.ts script
// DO NOT edit this file manually!!!

export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
}

export enum Permission {
  MANAGE_OWN_LEADS = "MANAGE_OWN_LEADS",
  EDIT_WORKSPACE_LEADS = "EDIT_WORKSPACE_LEADS",
  DELETE_WORKSPACE_LEADS = "DELETE_WORKSPACE_LEADS",
  ASSIGN_LEADS = "ASSIGN_LEADS",
  MANAGE_USERS = "MANAGE_USERS",
  VIEW_BILLING = "VIEW_BILLING",
  CREATE_BILLING = "CREATE_BILLING",
  EDIT_BILLING = "EDIT_BILLING",
  DELETE_BILLING = "DELETE_BILLING",
}

export enum LeadStatus {
  NEW = "NEW",
  INPROGRESS = "INPROGRESS",
  LOST = "LOST",
}

export enum ActivityType {
  EMAIL = "EMAIL",
  CALL = "CALL",
  MEETING = "MEETING",
  TASK = "TASK",
  NOTE = "NOTE",
  OTHER = "OTHER",
}
