export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
  MANAGER = "MANAGER"
}

export enum Permission {
  MANAGE_OWN_LEADS = "MANAGE_OWN_LEADS",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_BILLING = "MANAGE_BILLING",
  EDIT_WORKSPACE_LEADS = "EDIT_WORKSPACE_LEADS",
  DELETE_WORKSPACE_LEADS = "DELETE_WORKSPACE_LEADS",
  ASSIGN_LEADS = "ASSIGN_LEADS",
  VIEW_BILLING = "VIEW_BILLING",
  CREATE_BILLING = "CREATE_BILLING",
  EDIT_BILLING = "EDIT_BILLING",
  DELETE_BILLING = "DELETE_BILLING"
}

export enum LeadStatus {
  NEW = "NEW",
  INPROGRESS = "INPROGRESS",
  LOST = "LOST"
}

export enum ActivityType {
  EMAIL = "EMAIL",
  CALL = "CALL",
  MEETING = "MEETING",
  TASK = "TASK",
  NOTE = "NOTE",
  OTHER = "OTHER"
}

export enum ClientStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PROSPECT = "PROSPECT"
}

export enum ClientPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  VIP = "VIP"
}

export enum BillingStatus {
  PENDING = "PENDING",
  PAID = "PAID",
  OVERDUE = "OVERDUE"
}

