name: Deploy to Production
permissions:
  contents: read
on:
  push:
    branches: [main, production]
  workflow_dispatch:

jobs:
  build-and-install:
    name: Build Shared Package and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Build shared package
        run: |
          cd shared
          npm install
          npm run build

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Install server dependencies
        run: |
          cd server
          npm install

  migrate-database:
    name: Run Prisma Migrations
    runs-on: ubuntu-latest
    needs: build-and-install

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Build shared package
        run: |
          cd shared
          npm install
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run Prisma migrations
        run: |
          cd server
          npm run migrate:prod
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Add other environment variables as needed
