name: Pre-Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Migrate Prisma
      - run: cd server && npm run migrate:prod
